# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
        - Acme\AuthenticationBundle\Token\CustomAuthenticationToken
    
    google:
        enabled: true
        server_name: local.host     #le domaine/url de ton appli
        issuer: Météo Efrei         # nom qui s’affichera dans Google Auth
        digits: 6                   # nombre de chiffres du code (par défaut 6)
        leeway: 0                   # tolérance de décalage (en secondes)